spring:
  datasource:
    url: jdbc:h2:mem:test;DB_CLOSE_DELAY=-1
    username: sa
    password:
    driver-class-name: org.h2.Driver


#spring:
##  jpa:
##    database: postgresql
##    show-sql: true
##    generate-ddl: true
##    hibernate:
##      ddl-auto: #create-drop
##    properties:
##      hibernate:
##        dialect: org.hibernate.dialect.PostgreSQLDialect
##  flyway:
##    baselineOnMigrate: true
##    locations: filesystem:db/migration
##  datasource:
##    url: jdbc:postgresql://localhost:5432/clinic_registration
##    username: postgres
##    password: postgres
##    driver-class-name: org.postgresql.Driver
##
##server:
##  error:
##    include-message: always#


